version: "3.7"
services:
  etcdv3:
    image: bitnami/etcd:3.5
    restart: on-failure
    volumes:
       - ./data:/bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - "2379:2379"