version: '3.7'
services:
  mongo:
    image: mongo:4.0.4
    restart: on-failure
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    ports:
      - "27017:27017"