version: '3.7'
services:
   mysql:
     image: mysql:8.0
     restart: on-failure
     volumes:
       - ./data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
     ports:
       - 3306:3306
     command: 
       - --character-set-server=utf8mb4
       - --collation-server=utf8mb4_unicode_ci